# Generated by Django 6.0.4 on 2026-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda', 'Boda-boda')], max_length=30)),
                ('number_plate', models.CharField(max_length=10)),
                ('model_color', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(default='parked', max_length=20)),
            ],
        ),
    ]
