# Generated by Django 6.0.4 on 2026-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
