# Generated by Django 6.0.4 on 2026-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('PARKING ATTENDANT', 'Parking Attendant'), ('SECTION MANAGER', 'Section Manager'), ('SYSTEM ADMIN', 'System Admin')], max_length=50),
        ),
    ]
